name: Tests

on:
  push:
    branches: ["main", "v1.*"]
  pull_request:
    branches: ["main", "v1.*"]

jobs:
  test:
    name: Test using npm test & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test using Node v24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - run: npm test
      - run: npm run lint
